### ISSUE TITLE
[FR ii-qs] wayland-idle-inhibitor exits when sidebar is unloaded

### ISSUE THREAD

**Issue by Yossefosman** [end-4/dots-hyprland#1381]
### Step 1. Before you submit

- [x] I have read the [Troubleshooting](https://end-4.github.io/dots-hyprland-wiki/en/i-i/04troubleshooting/) and [Usage](https://end-4.github.io/dots-hyprland-wiki/en/i-i/02usage/) pages.
- [x] I've successfully updated to the latest version following the [guidance](https://end-4.github.io/dots-hyprland-wiki/en/i-i/01setup/#updating).
- [x] I've successfully updated the system packages to the latest.
- [ ] I've ticked the checkboxes without reading their contents

### Step 2. Quick diagnose info

<details><summary>Quick diagnose</summary>

/========================\
| Checking git repo info |
\========================/

[===diagnose===] git remote get-url origin
https://github.com/end-4/dots-hyprland.git
[---SUCCESS---]

[===diagnose===] git rev-parse HEAD
de941d8b9ede4c77826d942dfb5eb7e1ed987e8e
[---SUCCESS---]

/=================\
| Checking distro |
\=================/

[===diagnose===] ii_check_distro
LSB Version:	n/a
Distributor ID:	EndeavourOS
Description:	EndeavourOS Linux
Release:	rolling
Codename:	rolling
[---SUCCESS---]

/====================\
| Checking variables |
\====================/

[===diagnose===] declare -p XDG_CACHE_HOME
declare -x XDG_CACHE_HOME="/home/end/.cache"
[---SUCCESS---]

[===diagnose===] declare -p XDG_CONFIG_HOME
declare -x XDG_CONFIG_HOME="/home/end/.config"
[---SUCCESS---]

[===diagnose===] declare -p XDG_DATA_HOME
declare -x XDG_DATA_HOME="/home/end/.local/share"
[---SUCCESS---]

[===diagnose===] declare -p XDG_STATE_HOME
declare -x XDG_STATE_HOME="/home/end/.local/state"
[---SUCCESS---]

[===diagnose===] declare -p ILLOGICAL_IMPULSE_VIRTUAL_ENV
declare -x ILLOGICAL_IMPULSE_VIRTUAL_ENV="/home/end/.local/state/quickshell/.venv"
[---SUCCESS---]

/============================\
| Checking directories/files |
\============================/

[===diagnose===] ls -l /home/end/.local/state/quickshell/.venv
total 12
-rw-r--r-- 1 end end  43 Jun 10 12:30 CACHEDIR.TAG
drwxr-xr-x 1 end end 380 Jun 10 12:30 bin
drwxr-xr-x 1 end end  20 Jun 10 12:30 lib
lrwxrwxrwx 1 end end   3 Jun 10 12:30 lib64 -> lib
-rw-r--r-- 1 end end 189 Jun 10 12:30 pyvenv.cfg
[---SUCCESS---]

/===================\
| Checking versions |
\===================/

[===diagnose===] Hyprland --version
Hyprland 0.49.0 built from branch  at commit 9958d297641b5c84dcff93f9039d80a5ad37ab00  (version: bump to 0.49.0).
Date: Thu May 8 20:15:18 2025
Tag: v0.49.0, commits: 6098
built against:
 aquamarine 0.8.0
 hyprlang 0.6.3
 hyprutils 0.7.1
 hyprcursor 0.1.12
 hyprgraphics 0.1.3

no flags were set

[---SUCCESS---]

/==============================================\
| Finished. Output saved as "diagnose.result". |
\==============================================/

</details>

Closing Right

### Step 3. Describe the issue

<details><summary>Logs</summary>

```
<!-- Put your log content here!-->
```

</details>
Closing Sidebar causes wayland-idle-inhibitor to exit

### Reminder

- [x] I agree that it's usually impossible for others to help me without my logs.

**Comment by 0xarch** [comment]
in `.config/quickshell/modules/sidebarRight`, 53~55:
```qml
id: sidebarContentLoader
active: GlobalStates.sidebarRightOpen
anchors {
```

Change `active: GlobalStates.sidebarRightOpen` to `active:true` may solve this problem temporaily. This also fixes a bug that Gamemode button is always off when re-opening the sidebar.

(I don't know if this is the correct way. But since `sidebarRight` is controlled by `LazyLoader` in `.config/quickshell/shell.qml`, I think it's not really needed to use a `Loader` here)

**Comment by Yossefosman** [comment]
Thanks changing active:true worked
I was searching for a way with https://quickshell.outfoxxed.me/docs/types/Quickshell.Io/Process/#startDetached
but that won't be able to check if the process is running
will continue looking into

**Comment by 0xarch** [comment]
It seems the sidebar content instance is destoryed after closing... I don't know if the process spawned by `Process` is also killed that way. `startDetached` makes tracking hard, that might not be a good idea.

**Comment by end-4** [comment]
we can use the destruction of the sidebar to our advantage: check the running state every time it's initialized on open with `pidof`

**Comment by end-4** [comment]
should be fixed now, reopen if not

**Comment by 0xarch** [comment]
@end-4 Tested and the inhibitor works fine, but the gamemode toggle still can't remember it's state

**Comment by end-4** [comment]
> [@end-4](https://github.com/end-4) Tested and the inhibitor works fine, but the gamemode toggle still can't remember it's state

i forgot to say but this is fixed
