### ISSUE TITLE
Many issues with the new dotfiles that use quickshelll

### ISSUE THREAD

**Issue by Developer123-bit** [end-4/dots-hyprland#1556]
### Step 1. Before you submit

- [x] I have read the [Troubleshooting](https://end-4.github.io/dots-hyprland-wiki/en/ii-qs/04troubleshooting/) and [Usage](https://end-4.github.io/dots-hyprland-wiki/en/ii-qs/02usage/) pages.
- [x] I've successfully updated to the latest version following the [guidance](https://end-4.github.io/dots-hyprland-wiki/en/ii-qs/01setup/#updating).
- [x] I've successfully updated the system packages to the latest.
- [ ] I've ticked the checkboxes without reading their contents

### Step 2. Quick diagnose info
```
<!-- Run `./diagnose` inside the repo, and paste the result here! -->
```
/========================\
| Checking git repo info |
\========================/

[===diagnose===] git remote get-url origin
https://github.com/end-4/dots-hyprland/
[---SUCCESS---]

[===diagnose===] git rev-parse HEAD
9892e51e1d7d21767d603dfb408ffbed7cb76a05
[---SUCCESS---]

/=================\
| Checking distro |
\=================/

[===diagnose===] ii_check_distro
./diagnose: line 34: lsb_release: command not found
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo
[---SUCCESS---]

/====================\
| Checking variables |
\====================/

[===diagnose===] declare -p XDG_CACHE_HOME
./diagnose: line 30: declare: XDG_CACHE_HOME: not found
[---EXIT 1---]

[===diagnose===] declare -p XDG_CONFIG_HOME
./diagnose: line 30: declare: XDG_CONFIG_HOME: not found
[---EXIT 1---]

[===diagnose===] declare -p XDG_DATA_HOME
./diagnose: line 30: declare: XDG_DATA_HOME: not found
[---EXIT 1---]

[===diagnose===] declare -p XDG_STATE_HOME
./diagnose: line 30: declare: XDG_STATE_HOME: not found
[---EXIT 1---]

[===diagnose===] declare -p ILLOGICAL_IMPULSE_VIRTUAL_ENV
declare -x ILLOGICAL_IMPULSE_VIRTUAL_ENV="~/.local/state/quickshell/.venv"
[---SUCCESS---]

/============================\
| Checking directories/files |
\============================/

[===diagnose===] ls -l /home/laurence/.local/state/quickshell/.venv
total 16
-rw-r--r-- 1 laurence laurence   43 Jul  1 18:11 CACHEDIR.TAG
drwxr-xr-x 2 laurence laurence 4096 Jul  1 18:11 bin
drwxr-xr-x 3 laurence laurence 4096 Jul  1 18:11 lib
lrwxrwxrwx 1 laurence laurence    3 Jul  1 18:11 lib64 -> lib
-rw-r--r-- 1 laurence laurence  192 Jul  1 18:11 pyvenv.cfg
[---SUCCESS---]

/===================\
| Checking versions |
\===================/

[===diagnose===] Hyprland --version
Hyprland 0.49.0 built from branch main at commit ee8978b961b9b02ed41bd7b6d1e91cc607b6b530  (flake.lock: update).
Date: Sun Jun 29 16:29:36 2025
Tag: v0.49.0-134-gee8978b96, commits: 6232
built against:
 aquamarine 0.8.0
 hyprlang 0.6.3
 hyprutils 0.8.0
 hyprcursor 0.1.12
 hyprgraphics 0.1.4

no flags were set

[---SUCCESS---]

/==============================================\
| Finished. Output saved as "diagnose.result". |
\==============================================/

</details>

### Step 3. Describe the issue

<details><summary>Quick diagnose</summary>

I am having a lot of issues with the new dot files, such as not being able to get the taskbar at the bottom of the screen as shown in the screenshots, the settings app does not work, it doesnt change the light theme or change it to dark theme, the widgets dont change in the bar, such as when i was using my headphones, i dont know why it showed the bluewidget with a cross (indicating that it was turned off), but my headphones were perfectly connected and they worked as expected, another issue is the themes, if my wallpaper is blue, the bar wont change to blue, or any other equavalent theme to it, it stayed in its default, brown/gray state. and sometimes the dark theme does not apply to everything, it just applies to 1 thing or more and the rest is white, not sure what thats about. and whenever i open chrome on my laptop screen, it has a different theme, as soon as i open it on my monitor, it looks ugly, its in its default chrome theme, when the settings have it set to use gtk themes, and yeah, also kitty is black

<details><summary>Logs</summary>

```
<!-- Put your log content here!-->
```

</details>

### Reminder

- [x] I agree that it's usually impossible for others to help me without my logs.

**Comment by 0pl1v10n** [comment]
![Image](https://github.com/user-attachments/assets/fbaf8bf2-64bb-4075-a20a-e12d95e3ae1c)

here is an example of my themes not working.

**Comment by end-4** [comment]
can confirm the themes problem, i'm looking into it

**Comment by softwaresocialist** [comment]
Same Issue for me the theme switcher doesnt seem to switch gtk themes (I may be wrong)

**Comment by end-4** [comment]
uhh i forgot to comment but install xdg-desktop-portal-gtk and it should be fixed

**Comment by 0pl1v10n** [comment]
its already installed, but it does not fix the bluetooth icon in the bar yet.

**Comment by 0pl1v10n** [comment]
also, i think it would be a better idea, to make dark mode and light mode actual clickable buttons, because.. well, they dont apply changes after clicking, which is fine, but even on exiting and relaunching the settings dont show up, so im not sure how im supposed to know that dark theme or light theme is enabled.

**Comment by Bugraern** [comment]
Same issue. When switching to light or dark theme, it does not switch constantly. After changing the wallpaper, the theme switches to dark or light.

**Comment by clsty** [comment]
It has been months and things has changed a lot. Closing as outdated.

Feel free to re-open if problem still exists.
