### ISSUE TITLE
No wallpaper previews in the new wallpaper selector

### ISSUE THREAD

**Issue by bagashiz** [end-4/dots-hyprland#1895]
### Step 1. Before you submit

- [x] I have read the [Troubleshooting](https://end-4.github.io/dots-hyprland-wiki/en/ii-qs/04troubleshooting/) and [Usage](https://end-4.github.io/dots-hyprland-wiki/en/ii-qs/02usage/) pages.
- [x] I've successfully updated to the latest version following the [guidance](https://end-4.github.io/dots-hyprland-wiki/en/ii-qs/01setup/#updating).
- [x] I've successfully updated the system packages to the latest.
- [ ] I've ticked the checkboxes without reading their contents

### Step 2. Quick diagnose info

<details><summary>Quick diagnose</summary>

```
<!-- Run `./diagnose` inside the repo, and paste the result here! -->
```
https://0x0.st/KHSX.result

</details>

### Step 3. Describe the issue

There is no image preview in the new wallpaper selector. image attached below:

<img width="1920" height="1200" alt="Image" src="https://github.com/user-attachments/assets/bed10fba-7da5-4a80-9699-f4fe58cbd926" />

<details><summary>Logs</summary>

```
<!-- Put your log content here!-->
```

</details>

### Reminder

- [x] I agree that it's usually impossible for others to help me without my logs.

**Comment by end-4** [comment]
Run `~/.config/quickshell/ii/scripts/thumbnails/thumbgen.py -d ~/Pictures/Wallpapers`
What does it say?

**Comment by bagashiz** [comment]
```
++ eval echo '~/.local/state/quickshell/.venv'
+++ echo /home/bagashiz/.local/state/quickshell/.venv
+ source /home/bagashiz/.local/state/quickshell/.venv/bin/activate
++ '[' -z '' ']'
++ '[' -n x ']'
++ SCRIPT_PATH=/home/bagashiz/.local/state/quickshell/.venv/bin/activate
++ '[' /home/bagashiz/.local/state/quickshell/.venv/bin/activate = /home/bagashiz/.config/quickshell/ii/scripts/thumbnails/thumbgen.py ']'
++ deactivate nondestructive
++ unset -f pydoc
++ '[' -z '' ']'
++ '[' -z '' ']'
++ hash -r
++ '[' -z '' ']'
++ unset VIRTUAL_ENV
++ unset VIRTUAL_ENV_PROMPT
++ '[' '!' nondestructive = nondestructive ']'
++ VIRTUAL_ENV=/home/bagashiz/.local/state/quickshell/.venv
++ '[' linux-gnu = cygwin ']'
++ '[' linux-gnu = msys ']'
++ export VIRTUAL_ENV
++ '[' -z '' ']'
++ unset SCRIPT_PATH
++ _OLD_VIRTUAL_PATH=/home/bagashiz/.local/share/mise/installs/usage/2.2.2:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
++ PATH=/home/bagashiz/.local/state/quickshell/.venv/bin:/home/bagashiz/.local/share/mise/installs/usage/2.2.2:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
++ export PATH
++ '[' x.venv '!=' x ']'
++ VIRTUAL_ENV_PROMPT=.venv
++ export VIRTUAL_ENV_PROMPT
++ '[' -z '' ']'
++ '[' -z 1 ']'
++ alias pydoc
++ true
++ hash -r
+ exec python -E /home/bagashiz/.config/quickshell/ii/scripts/thumbnails/thumbgen.py -d /home/bagashiz/Pictures/Wallpapers
Traceback (most recent call last):
  File "/home/bagashiz/.config/quickshell/ii/scripts/thumbnails/thumbgen.py", line 18, in <module>
    gi.require_version("GnomeDesktop", "3.0")
  File "/home/bagashiz/.local/state/quickshell/.venv/lib/python3.12/site-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace GnomeDesktop not available
```

**Comment by bagashiz** [comment]
fixed with installing `gnome-desktop` dependency https://archlinux.org/packages/extra/x86_64/gnome-desktop/

**Comment by end-4** [comment]
Yikes
Requiring GNOME for this to work is kind of disgusting
I guess I will use the not so proper but non-gnome way to generate thumbnails by default then...

**Comment by EvanSunde** [comment]
Even though its closed issue, but i am still facing this same issue even though i have gnome-desktop installed
i open wallpaper selector i get this error in terminal 

`WARN scene: QML ThumbnailImage at @modules/wallpaperSelector/WallpaperDirectoryItem.qml[65:38]: Cannot open: file:///home/evan/.cache/thumbnails/normal/c3025e21c048f391cb6b7890688e7b54.png`

also when i run `~/.config/quickshell/ii/scripts/thumbnails/thumbgen.py -d ~/Pictures/Wallpapers`

i get python click not found error even though python-click package is installed.

**Comment by end-4** [comment]
> i get python click not found error even though python-click package is installed.

Maybe you didn't say Yes when install.sh asks to install the python env? Either run it again skipping everything except that or cd into the repo, and run this 

```
git pull
source ~/.local/state/quickshell/.venv/bin/activate.fish
uv pip install -r scriptdata/requirements.txt
deactivate
```

**Comment by EvanSunde** [comment]
Ohhh maybe i missed that during update. I manually do git pull for updated
dots.
