### ISSUE TITLE
Hide anime wallpaper button

### ISSUE THREAD

**Issue by Murat65536** [end-4/dots-hyprland#1944]
### What would you like to be added?

Even when you turn off the `Weeb` option in the settings, the option to replace the background with a random anime wallpaper remains. This is pretty annoying for me since I sometimes want to change wallpapers frequently and find myself accidentally pressing `Random: Konachan` instead of `Choose file` since they're so close together.  Could setting `Weeb` to `No` please remove this button?

**Comment by hexqubit** [comment]
Yes, I feel the same

**Comment by end-4** [comment]
done in 801cd2e855c71abe69f3251884ad13fd5f446bcc

**Comment by MorningMC** [comment]
i still have this problem. do i need a manual update? (all packages are up to date)

**Comment by MorningMC** [comment]
i tried update .config/quickshell just now but nothing worked

**Comment by MorningMC** [comment]
ok solved
