### ISSUE TITLE
Hyprland update breaks some things.

### ISSUE THREAD

**Issue by Yunexiz** [end-4/dots-hyprland#1986]
### Step 1. Before you submit

- [x] I have read the [Troubleshooting](https://end-4.github.io/dots-hyprland-wiki/en/ii-qs/04troubleshooting/) and [Usage](https://end-4.github.io/dots-hyprland-wiki/en/ii-qs/02usage/) pages.
- [x] I've successfully updated to the latest version following the [guidance](https://end-4.github.io/dots-hyprland-wiki/en/ii-qs/01setup/#updating).
- [x] I've successfully updated the system packages to the latest.
- [ ] I've ticked the checkboxes without reading their contents

### Step 2. Quick diagnose info

<details><summary>Quick diagnose</summary>

```
/========================\
| Checking git repo info |
\========================/

[===diagnose===] git remote get-url origin
https://github.com/end-4/dots-hyprland
[---SUCCESS---]

[===diagnose===] git rev-parse HEAD
53b03af3e1195cbc58a786e918e050df4d0f316d
[---SUCCESS---]

/=================\
| Checking distro |
\=================/

[===diagnose===] ii_check_distro
/home/yu/.cache/dots-hyprland/diagnose: line 34: lsb_release: command not found
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo
[---SUCCESS---]

/====================\
| Checking variables |
\====================/

[===diagnose===] declare -p XDG_CACHE_HOME
/home/yu/.cache/dots-hyprland/diagnose: line 30: declare: XDG_CACHE_HOME: not found
[---EXIT 1---]

[===diagnose===] declare -p XDG_CONFIG_HOME
/home/yu/.cache/dots-hyprland/diagnose: line 30: declare: XDG_CONFIG_HOME: not found
[---EXIT 1---]

[===diagnose===] declare -p XDG_DATA_HOME
/home/yu/.cache/dots-hyprland/diagnose: line 30: declare: XDG_DATA_HOME: not found
[---EXIT 1---]

[===diagnose===] declare -p XDG_STATE_HOME
/home/yu/.cache/dots-hyprland/diagnose: line 30: declare: XDG_STATE_HOME: not found
[---EXIT 1---]

[===diagnose===] declare -p ILLOGICAL_IMPULSE_VIRTUAL_ENV
declare -x ILLOGICAL_IMPULSE_VIRTUAL_ENV="~/.local/state/quickshell/.venv"
[---SUCCESS---]

/============================\
| Checking directories/files |
\============================/

[===diagnose===] ls -l /home/yu/.local/state/quickshell/.venv
total 20
-rw-r--r-- 1 yu yu   43 Sep 14 05:07 CACHEDIR.TAG
drwxr-xr-x 2 yu yu 4096 Sep 14 05:07 bin
drwxr-xr-x 3 yu yu 4096 Sep 14 05:07 include
drwxr-xr-x 3 yu yu 4096 Sep 14 05:07 lib
lrwxrwxrwx 1 yu yu    3 Sep 14 05:07 lib64 -> lib
-rw-r--r-- 1 yu yu  188 Sep 14 05:07 pyvenv.cfg
[---SUCCESS---]

/===================\
| Checking versions |
\===================/

[===diagnose===] Hyprland --version
Hyprland 0.51.0 built from branch  at commit 46174f78b374b6cea669c48880877a8bdcf7802f  (version: bump to 0.51.0).
Date: Wed Sep 10 12:41:05 2025
Tag: v0.51.0, commits: 6418
built against:
 aquamarine 0.9.4
 hyprlang 0.6.3
 hyprutils 0.8.4
 hyprcursor 0.1.13
 hyprgraphics 0.1.5


no flags were set

[---SUCCESS---]

/==============================================\
| Finished. Output saved as "diagnose.result". |
\==============================================/
```

</details>

### Step 3. Describe the issue

Hyprland updated to 0.51.0 and a lot of errors started appearing related to non-existent config options in the general.conf. I checked and apparently the gesture system was revamped.

<details><summary>Logs</summary>

```
Config error in file /home/yu/.config/hypr/hyprland/general.conf at line 9: config option <gestures:workspace_swipe> does not exist.
Config error in file /home/yu/.config/hypr/hyprland/general.conf at line 11: config option <gestures:workspace_swipe_fingers> does not exist.
Config error in file /home/yu/.config/hypr/hyprland/general.conf at line 12: config option <gestures:workspace_swipe_min_fingers> does not exist.
Config error in file /home/yu/.config/hypr/hyprland.conf at line 11: Config error in file /home/yu/.config/hypr/hyprland/general.conf at line 9: config option <gestures:workspace_swipe> does not exist.
// Pretty much the same errors again.
```

</details>

### Reminder

- [x] I agree that it's usually impossible for others to help me without my logs.

**Comment by Hopeful-ly** [comment]
It's mentioned [here](https://github.com/hyprwm/Hyprland/issues/8424#issuecomment-3242360162) as a breaking change.
And heres the hyprland PR: https://github.com/hyprwm/Hyprland/pull/11490

and it's fixed in https://github.com/end-4/dots-hyprland/pull/1892
and it's discussed here https://github.com/end-4/dots-hyprland/issues/1965 as well.

You should supposedly able to[ fix it by updating the configs](https://github.com/end-4/dots-hyprland/issues/1965#issuecomment-3282754838).

**Comment by Yunexiz** [comment]
I did try updating but it didn't fix it. I've just commented out the gesture in the config. I'll try again.

**Comment by LopesLs** [comment]
> I did try updating but it didn't fix it. I've just commented out the gesture in the config. I'll try again.

After update the problem was solved for me.
