### ISSUE TITLE
[Feature] Button to Mute/Unmute Mic in top-bar

### ISSUE THREAD

**Issue by Yasuhan** [end-4/dots-hyprland#367]
**What would you like to be added?**
I'd like to have a button in the top bar (maybe next to the ethernet/bluetooth icons), that on-click mutes/unmutes the microphone. 

**How will it help**
I use this rice on  my  work rig as well, and sometimes I need to quickly mute/unmute myself in meetings or Mumble even when the window is hidden/covered by something else. A mute button for the mic that's accessible from all my screens with just one simple click would be the perfect solution to that for me, and I would also see at a glance if my mic is on/off. It also helps, that it would be a global mute, with so many different things I sometime lose track what I'm actually talking on right now.

**Extra info**
![image](https://github.com/end-4/dots-hyprland/assets/30007466/e29221d9-ea5f-4cad-b000-36c2352ae65f)
Something likes this, to see it at a glance is super helpful for work setups.

**Comment by end-4** [comment]
There are 2 solutions I'm thinking of:
1. Have a "no mic" icon on the left of the Network icon if mic is muted globally. Muting/unmuting would be toggled with a keybind, but not mouse, since that area is for indicators only and mouse control is reserved for sidebar toggle and media actions
2. Have that thing as a tray item. This way I'm fine with it being clickable. A quick search returns this app https://github.com/Junker/mictray , but I've tested it and the tray item doesn't show up.

**Comment by end-4** [comment]
ooh, there's a list on arch wiki for what we're looking for: https://wiki.archlinux.org/title/PulseAudio#Graphical
so far kmix works and pasystray segfaults. i'm just lazy to test others

**Comment by Yasuhan** [comment]
The previous rice I used had waybar and used something akin to this:

`# Toggle Mic
toggle_mic() {
	if [ "$(pamixer --default-source --get-mute)" == "false" ]; then
		pamixer --default-source -m && notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "$iDIR/microphone-mute.png" "Microphone Switched OFF"
	elif [ "$(pamixer --default-source --get-mute)" == "true" ]; then
		pamixer -u --default-source u && notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "$iDIR/microphone.png" "Microphone Switched ON"
	fi
}`

Not sure how you'd best implement that into AGS though?

**Comment by end-4** [comment]
to format wrap in a code block with 3 backticks, like this:
\`\`\`bash
# write code here
# that "bash" there is the language name
\`\`\`

**Comment by end-4** [comment]
anyway i'm going to implement the 1st solution real quick

**Comment by end-4** [comment]
now, what keybind should i use :thinking:

**Comment by Yasuhan** [comment]
I'd probably put it on Super+XF86AudioMute?

**Comment by end-4** [comment]
sure

**Comment by end-4** [comment]
done
test it please?

**Comment by Yasuhan** [comment]
The keybind works, I just don't get the icon.

**Comment by end-4** [comment]
what

https://github.com/end-4/dots-hyprland/assets/97237370/8d671977-f76d-4d1b-9db4-107bd890a192

**Comment by Yasuhan** [comment]
Yeah..that doesn't happen for me. :sweat_smile:

**Comment by end-4** [comment]
did you update the ags config? is there anything in the logs? can you open a terminal, run `pkill ags; ags` and show the output?

**Comment by Yasuhan** [comment]
![image](https://github.com/end-4/dots-hyprland/assets/30007466/09d45747-8b77-41c5-bbea-d8bc02b35f0f)

https://github.com/end-4/dots-hyprland/assets/30007466/0fadc94c-b0a8-4911-a6dc-8424767c2ee5

Config updated, since the bluetooth toggles you added earlier also just appeared.

**Comment by end-4** [comment]
just commited 7a9f25aa99e72d642ed6cd387aefb85eee723090 which i think should fix it
try again

**Comment by Yasuhan** [comment]
It fixed the logs, but now I only have the bar on my main monitor and the icon still isn't loading.

**Comment by Yasuhan** [comment]
I fixed it by changing 

`Audio.microphone.isMuted`

to

`Audio.microphone.stream.is_muted`

as that seems to be the proper way to do it? https://github.com/Aylur/ags/issues/123

Only have the issue that I now get this: 

```

(com.github.Aylur.ags:33404): Gjs-CRITICAL **: 17:56:33.465: JS ERROR: TypeError: (intermediate value).microphone.stream is null```

The toggle works fine though..so no clue what's up there.

**Comment by Yasuhan** [comment]
Ah, perfect. Changing that now completely fixed it and no more errors appear. Thanks!

**Comment by end-4** [comment]
i guess that'll do it
