### ISSUE TITLE
[Issue] Fresh Arch install and nothing is working?

### ISSUE THREAD

**Issue by peperonnii** [end-4/dots-hyprland#468]
- **I have read the [Usage](https://end-4.github.io/dots-hyprland-wiki/en/i-i/02usage) and the [Troubleshooting](https://end-4.github.io/dots-hyprland-wiki/en/i-i/03troubleshooting) pages of the wiki**
- **I have made sure that both my config and system packages are up to date**
- Linux distro:  ARCH LINUX
---
## The issue
After resolving an issue with installing hyprland-git that prevented install.sh from installing the dotfiles. i got into hyprland from tty and ags did not boot up at all. im also getting a hyprland config error. cant ss because it wont let me.
`config error in file hyprland/colors.conf at line 9 rgba() expects length of 8 characters or 4 comma separated values`

here is what is output when ags is ran manually with pkill ags; ags 
```
(com.github.Aylur.ags:10295): Gtk-WARNING **: 22:18:22.372: Theme parsing error: gtk.css:95:30: '' is not a valid color name

(com.github.Aylur.ags:10295): Gtk-WARNING **: 22:18:22.372: Theme parsing error: gtk.css:95:44: Expected a valid selector

(com.github.Aylur.ags:10295): Gtk-WARNING **: 22:18:22.372: Theme parsing error: gtk.css:96:46: Expected a valid selector

(com.github.Aylur.ags:10295): Gtk-WARNING **: 22:18:22.372: Theme parsing error: gtk.css:97:41: Expected a valid selector

(com.github.Aylur.ags:10295): Gtk-WARNING **: 22:18:22.372: Theme parsing error: gtk.css:98:47: Expected a valid selector

(com.github.Aylur.ags:10295): Gtk-WARNING **: 22:18:22.372: Theme parsing error: gtk.css:99:49: Expected a valid selector

(com.github.Aylur.ags:10295): Gtk-WARNING **: 22:18:22.372: Theme parsing error: gtk.css:100:44: Expected a valid selector

(com.github.Aylur.ags:10295): Gtk-WARNING **: 22:18:22.372: Theme parsing error: gtk.css:105:41: Expected a valid selector

(com.github.Aylur.ags:10295): Gtk-WARNING **: 22:18:22.372: Theme parsing error: gtk.css:106:43: Expected a valid selector

(com.github.Aylur.ags:10295): Gtk-WARNING **: 22:18:22.372: Theme parsing error: gtk.css:107:47: Expected a valid selector

(com.github.Aylur.ags:10295): Gtk-WARNING **: 22:18:22.372: Theme parsing error: gtk.css:108:49: Expected a valid selector

(com.github.Aylur.ags:10295): Gtk-WARNING **: 22:18:22.372: Theme parsing error: gtk.css:109:42: Expected a valid selector

(com.github.Aylur.ags:10295): Gtk-WARNING **: 22:18:22.372: Theme parsing error: gtk.css:110:44: Expected a valid selector

(com.github.Aylur.ags:10295): Gtk-WARNING **: 22:18:22.372: Theme parsing error: gtk.css:112:60: Expected a valid selector

(com.github.Aylur.ags:10295): Gtk-WARNING **: 22:18:22.372: Theme parsing error: gtk.css:113:62: Expected a valid selector

(com.github.Aylur.ags:10295): Gtk-WARNING **: 22:18:22.372: Theme parsing error: gtk.css:116:45: Expected a valid selector

(com.github.Aylur.ags:10295): Gtk-WARNING **: 22:18:22.372: Theme parsing error: gtk.css:117:55: Expected a valid selector

(com.github.Aylur.ags:10295): Gtk-WARNING **: 22:18:22.372: Theme parsing error: gtk.css:119:55: Expected a valid selector

(com.github.Aylur.ags:10295): Gtk-WARNING **: 22:18:22.372: Theme parsing error: gtk.css:120:57: Expected a valid selector

(com.github.Aylur.ags:10295): Gtk-WARNING **: 22:18:22.372: Theme parsing error: gtk.css:121:56: Expected a valid selector

(com.github.Aylur.ags:10295): Gtk-WARNING **: 22:18:22.372: Theme parsing error: gtk.css:122:58: Expected a valid selector

** (com.github.Aylur.ags:10295): WARNING **: 22:18:22.457: Failed to load shared library 'libgvc.so' referenced by the typelib: libgvc.so: cannot open shared object file: No such file or directory

(com.github.Aylur.ags:10295): Gjs-WARNING **: 22:18:22.457: JS ERROR: Error: Unsupported type void, deriving from fundamental void
Audio@resource:///com/github/Aylur/ags/service/audio.js:114:9
@resource:///com/github/Aylur/ags/service/audio.js:201:15
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
```

fonts don't seem to be installed correctly either in terminal. there is no wallpaper. basically nothing works. this is my first time installing so i dont really know what its really supposed to look like. I've tried looking at other Issues and people seem to be having all these issues today. Is there a way I can use a slightly older build?

<details>
<summary>Click to expand</summary>

```plain
Paste your log here
```

</details>

**Comment by pepperonipizzah** [comment]
it's not meant to do this right.. 😭

![20240502_233313](https://github.com/end-4/dots-hyprland/assets/76881322/0dbbf8dd-4804-4d7a-8330-646686dd974e)
![20240502_233246](https://github.com/end-4/dots-hyprland/assets/76881322/44cc6484-e3a3-4624-a85a-bcf1aef2092c)

**Comment by idiom444** [comment]
I have the same issue. I saw in another thread suggesting that adding ~/.cache/ags/user/colormode.txt as described here https://github.com/end-4/dots-hyprland/issues/350. I did not have this file so i tried this and it made some of the widgets load but their styling is clearly broken and i doubt all of them are there (first time using end-4) and i also have the same error message you see on your screen as well. Fresh arch install.

**Comment by pepperonipizzah** [comment]
yeah it seems completely broken...

**Comment by arqueon** [comment]
Same for me, I fixed the hyprland compilation, also there was a problem wit ags, I finally installed it, install finished but only a black screen, no toolbars, but I was able to run foot via Supert-T, but not anymore.

**Comment by playerz-unknowns** [comment]
> Same for me, I fixed the hyprland compilation, also there was a problem wit ags, I finally installed it, install finished but only a black screen, no toolbars, but I was able to run foot via Supert-T, but not any much more. I tried the same install with endeavour-gnome and pure arch linux.

had the same issue yesterday,reinstalled the exact same way and the issue solved by itself,i think its a problem with package versions.
if you have errors while compiling,maybe try using chaotic-aur,saves a ton of time

**Comment by pepperonipizzah** [comment]
> > Same for me, I fixed the hyprland compilation, also there was a problem wit ags, I finally installed it, install finished but only a black screen, no toolbars, but I was able to run foot via Supert-T, but not any much more. I tried the same install with endeavour-gnome and pure arch linux.
> 
> had the same issue yesterday,reinstalled the exact same way and the issue solved by itself,i think its a problem with package versions. if you have errors while compiling,maybe try using chaotic-aur,saves a ton of time

Could you explain how to use that?

**Comment by idiom444** [comment]
> I have the same issue. To attempt to solve this i have tried these solutions:
> 
>     * [[Issue] ags not running  #350](https://github.com/end-4/dots-hyprland/issues/350) add colormode.txt
> 
>     * [[Issue] Changing wallpaper or changing things from sidebar live config causes loss of styling #452](https://github.com/end-4/dots-hyprland/issues/452)
> 
>     * [[Issue] Ags & cursor related problem #465](https://github.com/end-4/dots-hyprland/issues/465)
> 
> 
> The first made some of the widgets load but they are very broken and i also have the same error message you see on your screen. Fresh arch install.
> 
> In case it is relevant i had this issue as well #461 I ended up skipping hyprland-git and running yay -S hyprland

So i have tried fresh install a couple times since my last comment. The latest time i went through the manual install instructions and still get the same situation. I managed to build hyperland-git this time instead of hyperland and all the dependencies were successful.

Here is my pkill ags;ags:

<details>
  <summary>pkill output</summary>
(com.github.Aylur.ags:3968): Gtk-WARNING **: 23:29:22.519: Theme parsing error: gtk.css:95:30: '' is not a valid color name

(com.github.Aylur.ags:3968): Gtk-WARNING **: 23:29:22.519: Theme parsing error: gtk.css:95:44: Expected a valid selector

(com.github.Aylur.ags:3968): Gtk-WARNING **: 23:29:22.519: Theme parsing error: gtk.css:96:46: Expected a valid selector

(com.github.Aylur.ags:3968): Gtk-WARNING **: 23:29:22.519: Theme parsing error: gtk.css:97:41: Expected a valid selector

(com.github.Aylur.ags:3968): Gtk-WARNING **: 23:29:22.519: Theme parsing error: gtk.css:98:47: Expected a valid selector

(com.github.Aylur.ags:3968): Gtk-WARNING **: 23:29:22.519: Theme parsing error: gtk.css:99:49: Expected a valid selector

(com.github.Aylur.ags:3968): Gtk-WARNING **: 23:29:22.519: Theme parsing error: gtk.css:100:44: Expected a valid selector

(com.github.Aylur.ags:3968): Gtk-WARNING **: 23:29:22.519: Theme parsing error: gtk.css:105:41: Expected a valid selector

(com.github.Aylur.ags:3968): Gtk-WARNING **: 23:29:22.519: Theme parsing error: gtk.css:106:43: Expected a valid selector

(com.github.Aylur.ags:3968): Gtk-WARNING **: 23:29:22.519: Theme parsing error: gtk.css:107:47: Expected a valid selector

(com.github.Aylur.ags:3968): Gtk-WARNING **: 23:29:22.519: Theme parsing error: gtk.css:108:49: Expected a valid selector

(com.github.Aylur.ags:3968): Gtk-WARNING **: 23:29:22.519: Theme parsing error: gtk.css:109:42: Expected a valid selector

(com.github.Aylur.ags:3968): Gtk-WARNING **: 23:29:22.519: Theme parsing error: gtk.css:110:44: Expected a valid selector

(com.github.Aylur.ags:3968): Gtk-WARNING **: 23:29:22.519: Theme parsing error: gtk.css:112:60: Expected a valid selector

(com.github.Aylur.ags:3968): Gtk-WARNING **: 23:29:22.519: Theme parsing error: gtk.css:113:62: Expected a valid selector

(com.github.Aylur.ags:3968): Gtk-WARNING **: 23:29:22.519: Theme parsing error: gtk.css:116:45: Expected a valid selector

(com.github.Aylur.ags:3968): Gtk-WARNING **: 23:29:22.519: Theme parsing error: gtk.css:117:55: Expected a valid selector

(com.github.Aylur.ags:3968): Gtk-WARNING **: 23:29:22.519: Theme parsing error: gtk.css:119:55: Expected a valid selector

(com.github.Aylur.ags:3968): Gtk-WARNING **: 23:29:22.519: Theme parsing error: gtk.css:120:57: Expected a valid selector

(com.github.Aylur.ags:3968): Gtk-WARNING **: 23:29:22.519: Theme parsing error: gtk.css:121:56: Expected a valid selector

(com.github.Aylur.ags:3968): Gtk-WARNING **: 23:29:22.519: Theme parsing error: gtk.css:122:58: Expected a valid selector

(com.github.Aylur.ags:3968): Gjs-Console-WARNING **: 23:29:22.594: Error: can't assign "chromium-browser" as icon, it is not a file nor a named icon
set icon@resource:///com/github/Aylur/ags/widgets/icon.js:45:30
_handleParamProp@resource:///com/github/Aylur/ags/widgets/widget.js:124:13
Icon@resource:///com/github/Aylur/ags/widgets/icon.js:25:14
newIcon@resource:///com/github/Aylur/ags/widgets/icon.js:8:12
ElementTile@file:///home/Idiom/.config/ags/modules/cheatsheet/periodictable.js:26:32
default/mainBoard<.children</<.children<@file:///home/Idiom/.config/ags/modules/cheatsheet/periodictable.js:62:58
default/mainBoard<.children<@file:///home/Idiom/.config/ags/modules/cheatsheet/periodictable.js:62:27
default@file:///home/Idiom/.config/ags/modules/cheatsheet/periodictable.js:60:33
@file:///home/Idiom/.config/ags/modules/cheatsheet/main.js:18:24
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
  


(com.github.Aylur.ags:3968): Gjs-Console-CRITICAL **: 23:29:22.817: Error: There is no window named overview
getWindow@resource:///com/github/Aylur/ags/app.js:140:27
update@file:///home/Idiom/.config/ags/modules/overview/overview_hyprland.js:334:26
default/OverviewRow/setup/<@file:///home/Idiom/.config/ags/modules/overview/overview_hyprland.js:377:60
hook/<@resource:///com/github/Aylur/ags/widgets/widget.js:43:25
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
  

(com.github.Aylur.ags:3968): Gjs-Console-CRITICAL **: 23:29:22.817: Error: There is no window named overview
getWindow@resource:///com/github/Aylur/ags/app.js:140:27
update@file:///home/Idiom/.config/ags/modules/overview/overview_hyprland.js:334:26
default/OverviewRow/setup/<@file:///home/Idiom/.config/ags/modules/overview/overview_hyprland.js:398:39
hook/<@resource:///com/github/Aylur/ags/widgets/widget.js:43:25
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
  

(com.github.Aylur.ags:3968): Gjs-Console-CRITICAL **: 23:29:22.817: Error: There is no window named overview
getWindow@resource:///com/github/Aylur/ags/app.js:140:27
update@file:///home/Idiom/.config/ags/modules/overview/overview_hyprland.js:334:26
default/OverviewRow/setup/<@file:///home/Idiom/.config/ags/modules/overview/overview_hyprland.js:377:60
hook/<@resource:///com/github/Aylur/ags/widgets/widget.js:43:25
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
  

(com.github.Aylur.ags:3968): Gjs-Console-CRITICAL **: 23:29:22.817: Error: There is no window named overview
getWindow@resource:///com/github/Aylur/ags/app.js:140:27
update@file:///home/Idiom/.config/ags/modules/overview/overview_hyprland.js:334:26
default/OverviewRow/setup/<@file:///home/Idiom/.config/ags/modules/overview/overview_hyprland.js:398:39
hook/<@resource:///com/github/Aylur/ags/widgets/widget.js:43:25
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
  

(com.github.Aylur.ags:3968): Gjs-Console-CRITICAL **: 23:29:24.990: CSS ERROR: Invalid name of pseudo-class at line 8 in /home/Idiom/.cache/ags/user/generated/style.css

(com.github.Aylur.ags:3968): Gtk-WARNING **: 23:29:25.037: Attempting to add a widget with type Ags_Box to a container of type Ags_Box, but the widget is already inside a container of type Ags_Box, please remove the widget from its existing container first.

(com.github.Aylur.ags:3968): Gtk-WARNING **: 23:29:25.038: Attempting to add a widget with type Ags_Box to a container of type Ags_Box, but the widget is already inside a container of type Ags_Box, please remove the widget from its existing container first.
Gtk.CssProviderError: style.css:9:5Invalid name of pseudo-class

(com.github.Aylur.ags:3968): Gtk-WARNING **: 23:29:25.157: Attempting to add a widget with type Ags_Revealer to a container of type Ags_Box, but the widget is already inside a container of type Ags_Box, please remove the widget from its existing container first.

(com.github.Aylur.ags:3968): Gtk-WARNING **: 23:29:25.163: Attempting to add a widget with type Ags_Revealer to a container of type Ags_Box, but the widget is already inside a container of type Ags_Box, please remove the widget from its existing container first.

(com.github.Aylur.ags:3968): GLib-GObject-CRITICAL **: 23:29:25.184: value "1.525223" of type 'gdouble' is invalid or out of range for property 'fraction' of type 'gdouble'

(com.github.Aylur.ags:3968): GLib-GObject-CRITICAL **: 23:29:25.184: value "1.525223" of type 'gdouble' is invalid or out of range for property 'fraction' of type 'gdouble'

(com.github.Aylur.ags:3968): GLib-GObject-CRITICAL **: 23:29:25.184: value "1.525223" of type 'gdouble' is invalid or out of range for property 'fraction' of type 'gdouble'
</details>

**Comment by idiom444** [comment]
Hey I have been having this issue for some time now and my issue was not having a wallpaper set. CTRL + SUPER + T doesn't have any files there so I never set a wallpaper and i guess the rest of the setup needs one for its colors. Took me a crazy amount of time to figure this out lol.

**Comment by end-4** [comment]
looks like i need a crazier way to tell people to pick a wall then

**Comment by end-4** [comment]
![image](https://github.com/end-4/dots-hyprland/assets/97237370/4e651f1c-6865-4cf9-a5f7-87c768510e82)

**Comment by idiom444** [comment]
Yeah I tried that initially but there were no wall papers in the folder that opens so i kind of glossed over it for some time.

Downloaded some random picture and solved it.

**Comment by H0mire** [comment]
Yeah, having some default picture from Hyprland that automatically loads would be convenient.

**Comment by pepperonipizzah** [comment]
thanks for all the help. i really wanted to get this working because i love the look to these dotfiles. i would like to delve into the modules of ags but thats for another day.

i figured out that a wallpaper must be set after trial and error and around the same time people figured that out too lol.

A default wallpaper would be appreciated as i was completely clueless as to why it was not working on a fresh install. i was convinced the dotfiles were broken or smth. 

Thanks for all the input i appreciate it.
