### ISSUE TITLE
[Issue] Annoying "Update your config" notification

### ISSUE THREAD

**Issue by l4v3nx** [end-4/dots-hyprland#542]
- **I have read the [Usage](https://end-4.github.io/dots-hyprland-wiki/en/i-i/02usage) and the [Troubleshooting](https://end-4.github.io/dots-hyprland-wiki/en/i-i/03troubleshooting) pages of the wiki**
- **I have made sure that both my config and system packages are up to date**
- Linux distro: Arch Linux

---
## The issue

Whenever i login into Hyprland or reload ags, this notification is triggered
https://github.com/end-4/dots-hyprland/blob/e46dc5e1a4b1955aadcdd47965756c5dfb24267e/.config/ags/modules/.configuration/user_options.js#L192-L196

![image](https://github.com/end-4/dots-hyprland/assets/58698398/aadfac9b-9d06-47ec-aecc-1fdf78ef54ba)

How can i avoid triggering it? because i always think someone wrote me.
My user_options.js: https://github.com/l4v3nx/dots-hyprland/blob/main/.config/ags/user_options.js

**Comment by end-4** [comment]
change this
```js
    'sidebar': {
        'imageAllowNsfw': true,
    },
```
to this
```
    'sidebar': {
        'image': {
            'allowNsfw': true,
        },
    },
```

**Comment by end-4** [comment]
Note that currently that option does not work and nsfw will always be allowed by default for some reason :skull:
i should fix it

**Comment by l4v3nx** [comment]
it still shows up. can you check what i did wrong https://github.com/l4v3nx/dots-hyprland/commits/main/.config/ags/user_options.js

**Comment by end-4** [comment]
looks alright to me `¯\_(ツ)_/¯`

**Comment by l4v3nx** [comment]
well, i guess there's nothing i can do, so closing

**Comment by end-4** [comment]
okay, my bad. two flaws:

**Comment by end-4** [comment]
test plz 👉👈

**Comment by l4v3nx** [comment]
yep, this works fine. thanks

**Comment by l4v3nx** [comment]
@end-4 btw, do you know how to keep my fork up to date without adding such commits https://github.com/l4v3nx/dots-hyprland/commit/40a2de05dfab62be697b0e0139aa46f53f245d21 ?
like only merge your new commits saving commit time order without creating merge commits
